;;; crush-test-xxh3.el --- XXH3-64 tests for crush  -*- lexical-binding: t; -*-
;;; Copyright (C) 2026 Thomas Christensen

;;; Author: Thomas Christensen <thomasc1971@hotmail.com>
;;; URL: https://github.com/thomasc1971/crush.el
;;; Version: 0.1.0
;;; Package-Requires: ((emacs "28.1"))
;;; Keywords: tools, ai, convenience

;;; This file is not part of GNU Emacs.

;;; Permission is hereby granted, free of charge, to any person obtaining a copy
;;; of this software and associated documentation files (the "Software"), to deal
;;; in the Software without restriction, including without limitation the rights
;;; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
;;; copies of the Software, and to permit persons to whom the Software is
;;; furnished to do so, subject to the following conditions:

;;; The above copyright notice and this permission notice shall be included in all
;;; copies or substantial portions of the Software.

;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
;;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
;;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
;;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
;;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
;;; SOFTWARE.
;;; Commentary:
;;; Pure-Elisp XXH3-64 (seed 0) must byte-match the reference
;;; implementation (github.com/zeebo/xxh3, v1.1.0) that the Crush CLI
;;; uses for x-session-id / x-session-affinity (internal/session/session.go
;;; HashID: seed 0, big-endian Sum() hex).  The expected values below were
;;; generated by that exact library, so they pin the wire contract.

;;; Code:

(require 'ert)
(require 'cl-lib)

(require 'crush-xxh3)

(ert-deftest crush-test/xxh3-empty-string ()
  "The empty string hashes to zeebo/xxh3's value (2d06800538d394c2)."
  (should (string= (crush-xxh3-hash64 "") "2d06800538d394c2")))

(ert-deftest crush-test/xxh3-single-byte ()
  "A one-byte input hashes to zeebo/xxh3's value (eaf06c6480b2cd11)."
  (should (string= (crush-xxh3-hash64 "x") "eaf06c6480b2cd11")))

(ert-deftest crush-test/xxh3-short-string ()
  "A short ASCII input hashes to zeebo/xxh3's value (e84c92e9c14c5eb1)."
  (should (string= (crush-xxh3-hash64 "crush.el") "e84c92e9c14c5eb1")))

(ert-deftest crush-test/xxh3-mid-string ()
  "A typical sentence hashes to zeebo/xxh3's value (ce7d19a5418fb365)."
  (should (string= (crush-xxh3-hash64
                    "The quick brown fox jumps over the lazy dog")
                   "ce7d19a5418fb365")))

(ert-deftest crush-test/xxh3-uuid-shaped ()
  "The session-UUID shape used by Crush (f47ac10b...) hashes to
zeebo/xxh3's value (db22027126414ba6), the exact wire value for
x-session-id / x-session-affinity."
  (should (string= (crush-xxh3-hash64 "f47ac10b-58cc-4372-a567-0e02b2c3d479")
                   "db22027126414ba6")))

(ert-deftest crush-test/xxh3-long-string ()
  "A 48-byte input reaches the long-path (>= 48 bytes) of XXH3 and
hashes to zeebo/xxh3's value (e80a6fbd46bf1339)."
  (should (string= (crush-xxh3-hash64
                    "0123456789abcdef0123456789abcdef0123456789abcdef")
                   "e80a6fbd46bf1339")))

(ert-deftest crush-test/xxh3-output-shape ()
  "The output is 16 lowercase hex characters regardless of input."
  (dolist (input '("" "a" "abcdefghijklmnopqrstuvwxyz" "0123456789abcdef0123456789abcdef0123456789abcdef"))
    (let ((digest (crush-xxh3-hash64 input)))
      (should (= (length digest) 16))
      (should (string-match-p "\\`[0-9a-f]\\{16\\}\\'" digest)))))

(ert-deftest crush-test/xxh3-deterministic ()
  "The same input always hashes to the same value."
  (should (string= (crush-xxh3-hash64 "crush.el")
                   (crush-xxh3-hash64 "crush.el"))))

(ert-deftest crush-test/xxh3-beam-48-boundary ()
  "Inputs straddling the XXH3 48-byte long/short boundary are stable:
a 48-byte input and a 47-byte input both hash deterministically."
  (let ((s48 (make-string 48 ?a))
        (s47 (make-string 47 ?a)))
    (should (string= (crush-xxh3-hash64 s48) (crush-xxh3-hash64 s48)))
    (should (string= (crush-xxh3-hash64 s47) (crush-xxh3-hash64 s47)))
    (should-not (string= (crush-xxh3-hash64 s48) (crush-xxh3-hash64 s47)))))

(ert-deftest crush-test/xxh3-official-known-answers ()
  "The port matches the official XXH3-64 known-answer values from the
Cyan4973/xxHash reference implementation (independently of zeebo)."
  (let ((pairs '(("" . "2d06800538d394c2")
                 ("a" . "e6c632b61e964e1f")
                 ("abc" . "78af5f94892f3950")
                 ("message digest" . "160d8e9329be94f9")
                 ("abcdefghijklmnopqrstuvwxyz" . "810f9ca067fbb90c")
                 ("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
                  . "643542bb51639cb2")
                 ("12345678901234567890123456789012345678901234567890123456789012345678901234567890"
                  . "7f58aa2520c681f9"))))
    (dolist (pair pairs)
      (should (string= (crush-xxh3-hash64 (car pair)) (cdr pair))))))

(provide 'crush-test-xxh3)
;;; crush-test-xxh3.el ends here
